# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('full_name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Artist')),
            ],
            bases=('places.artist',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Artwork')),
                ('author', models.ManyToManyField(to='places.Author')),
            ],
            bases=('places.artwork',),
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Artist')),
            ],
            bases=('places.artist',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Artist')),
            ],
            bases=('places.artist',),
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Artist')),
            ],
            bases=('places.artist',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Artwork')),
                ('director', models.ManyToManyField(to='places.Director')),
                ('editor', models.ManyToManyField(to='places.Editor')),
            ],
            bases=('places.artwork',),
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Artist')),
            ],
            bases=('places.artist',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Artwork')),
                ('composer', models.ManyToManyField(to='places.Composer')),
                ('performer', models.ManyToManyField(to='places.Performer')),
            ],
            bases=('places.artwork',),
        ),
        migrations.AddField(
            model_name='scene',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.Artist'),
        ),
        migrations.AddField(
            model_name='scene',
            name='artwork',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.Artwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.Artist'),
        ),
    ]
