# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('composer', models.TextField(default='')),
                ('performer', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
