# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_scene_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='full_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scene',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
