# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_loc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loc',
        ),
    ]
