# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_delete_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='full_name',
            field=models.TextField(default='', unique=True),
        ),
    ]
