# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20170519_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.TextField(default=''),
        ),
    ]
