# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20170519_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='composer',
            new_name='composers',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='performer',
            new_name='performers',
        ),
    ]
